plugins {
    id 'java'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '5.3.9'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

ext {
    serenityVersion = '5.3.10'
    cucumberVersion = '7.34.2'
    junitVersion = '6.0.3'
}

dependencies {
    implementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    implementation "io.github.bonigarcia:webdrivermanager:5.9.2"

    testImplementation "net.serenity-bdd:serenity-ensure:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}"
    testImplementation "org.junit.platform:junit-platform-suite:${junitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
}

test {
    useJUnitPlatform()
    finalizedBy 'aggregate'
   // systemProperty 'cucumber.execution.parallel.enabled', 'true'
    //systemProperty 'cucumber.execution.parallel.config.strategy', 'fixed'
//    systemProperty 'cucumber.execution.parallel.config.fixed.parallelism', '4'
//    systemProperty 'cucumber.execution.parallel.config.fixed.max-pool-size', '4'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-parameters']
}
